### ISSUE TITLE
Kentico connector unavailable - you can't find it in the Google Data (Looker) Studio

### ISSUE THREAD

**Issue by alisiecka** [Kentico/xperience-google-lookerstudio#2]
### Brief bug description

Connector can't be found:

![image](https://user-images.githubusercontent.com/118433725/203576108-a32eb749-92ee-4758-8064-4257bb39e617.png)

### Repro steps

1. Go to ['...'](https://datastudio.google.com/)
2. Click on 'Create' > 'Data source'
3. Search for 'Kentico' or 'Xperience'
4. Nothing will be found

### Expected behavior

I expected the same result as described here: https://github.com/Kentico/xperience-google-datastudio#add-the-xperience-data-source-to-gds-reports
Which means that Kentico Xperience should appear as a search result.

### Test environment

 - Browser: Chrome
 - Version: 107.0.5304.107 

### Additional context

May be related with the switch made by Google some time ago - from Data Studio to Looker Studio. I've experienced a lot of changes/issues since this change occured.

**Comment by kentico-ericd** [comment]
Hello @alisiecka! I apologize for the issue- the verification process for the custom connector has been delayed for quite a long time. The connector won't be public until Google approves it, but if you'd like I can invite you to the project which will give you full access to the connector. I would just need an email address associated with a Google account!

**Comment by alisiecka** [comment]
Hello!
Would be great to have it indeed! Please use ***@***.******@***.***> – this one is connected to the Google account.

Many thanks 😊

**Comment by kentico-ericd** [comment]
@alisiecka I think your email address was removed by your SMTP (or GitHub's), can you try replying directly to this issue instead?

**Comment by alisiecka** [comment]
Hello, how about comment below, can you see it?
alisiecka[at]reference.be

**Comment by kentico-ericd** [comment]
Yes, that works! I've added you to the project so you should have access to the connector now. If it doesn't show up for some reason, [this link](https://datastudio.google.com/datasources/create?connectorId=AKfycbweYLlYyFlZxhfskpZzwmDs0w0CmFZQD-Rv-vd5dI4) might help

**Comment by ondrejhenek** [comment]
Cleaning up - the Looker Studio connector has been published a long time ago already.
